version: "3.8"
services:
  db:
    image: supabase/postgres:latest
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: mqIzet73GpNpxZ83
      POSTGRES_USER: yommexg
      POSTGRES_DB: qaesamqdgxoafccklqmx
    networks:
      - supabase_network

networks:
  supabase_network:
